### ISSUE TITLE
About PR approval policy

### ISSUE THREAD

**Issue by xshifty** [ddd-fellowship/php-task-manager#5]
Hello guys,

I think that is time to start the coding. But, before start, i want to define some PR acceptance policy.
What if we just accept a PR. just after 5 positive votes?

After 5 positive votes (negative votes count as -1), anyone from this **fellowship** can merge the PR?

I'll do something, and create our first PR with code (we need to define some structural concepts before).

**Comment by devdrops** [comment]
:+1:

I'd like to suggest the creation of a document specifying these requirements. Maybe a wiki page, what do you guys think? =D

And last but not least, what about using http://fabbot.io/?

**Comment by codeliner** [comment]
:+1: for voting

:+1: for a document, could be part of a CONTRIBUTION.md?

- not sure about fabbot, I've never used it so I can't say much about it - it just looks like it is made for symfony projects
